"""Paper node: read training/eval JSONs (all runs) -> LaTeX tables + prose -> patch paper.

Reads every experiments/training_results*.json + the latest evaluation to build
a per-run comparison table. Prose paragraphs are generated by the writer agent
(LLM) from the real numbers; tables themselves are pure data.
"""
import pathlib, json, re

def _load_json(path):
    if pathlib.Path(path).exists():
        return json.loads(pathlib.Path(path).read_text())
    return None

def _run_label(path):
    """training_results.json -> baseline, training_results_X.json -> X."""
    stem = path.stem.replace("training_results", "").strip("_")
    return stem or "baseline"

def _first_last(recs):
    if not recs:
        return 0.0, 0.0
    return recs[0].get("loss", 0.0), recs[-1].get("loss", 0.0)

def build_results_section(runs: dict, ev: dict, prose: dict | None = None):
    """runs: {label: [epoch_records]}; ev: evaluation dict; prose: {section: text}."""
    # Comparison table: one row per run
    rows = []
    for label, recs in runs.items():
        l0, l1 = _first_last(recs)
        last = recs[-1] if recs else {}
        top1 = last.get("val_top1")
        top1_s = f"{top1:.3f}" if isinstance(top1, (int, float)) else "--"
        ce = last.get("loss_ce")
        ce_s = f"{ce:.2f}" if isinstance(ce, (int, float)) else "--"
        mse = last.get("loss_mse")
        mse_s = f"{mse:.2f}" if isinstance(mse, (int, float)) else "--"
        rows.append(f"{label} & {l0:.2f} & {l1:.2f} & {ce_s} & {mse_s} & {top1_s} \\\\")
    cmp_table = ("\\begin{table}[h]\\centering\\caption{Training runs: total loss, "
                 "policy CE, value MSE (final epoch) and validation top-1.}"
                 "\\begin{tabular}{lccccc}\\hline Run & Loss$_{e0}$ & Loss$_{last}$ & CE & MSE & Top-1 \\\\ \\hline\n"
                 + "\n".join(rows) + "\n\\hline\\end{tabular}\\end{table}")

    ev_table, caveat = "", ""
    if isinstance(ev, dict):
        n_pos = ev.get("n_positions", "?")
        src = ev.get("source", "?")
        top1 = ev.get("top1_accuracy", 0)
        top3 = ev.get("top3_accuracy", 0)
        vmse = ev.get("value_mse", 0)
        caption = f"Held-out evaluation (n={n_pos}, source={src})"
        ev_table = (
            "\\begin{table}[h]\\centering\\caption{" + caption + "}"
            "\\begin{tabular}{lc}\\hline Metric & Value \\\\ \\hline "
            f"Top-1 Accuracy & {top1:.3f} \\\\ "
            f"Top-3 Accuracy & {top3:.3f} \\\\ "
            f"Value MSE & {vmse:.4f} \\\\ \\hline\\end{{tabular}}\\end{{table}}")
        if ev.get("verdict") == "NOT_FOR_PUBLICATION":
            caveat = ("\\noindent\\textbf{Caveat:} evaluation metrics above come from a "
                      f"small mock set (n={ev.get('n_positions','?')}); "
                      "they are pipeline smoke tests, not publishable results.\n")
    else:
        caveat = "\\noindent\\textbf{Caveat:} no evaluation results found.\n"

    prose = prose or {}
    intro = prose.get("results_intro", "")
    ev_prose = prose.get("eval_prose", "")
    attn = prose.get("attention_prose", "")

    return (f"\\section{{Results \\& Evaluation}}\n{intro}\n{cmp_table}\n\n{ev_table}\n"
            f"{caveat}{ev_prose}\n\n\\section{{Attention Analysis}}\n{attn}\n")

def gather_runs(base):
    exp = base / "experiments"
    runs = {}
    for p in sorted(exp.glob("training_results*.json")):
        if "smoke" in p.stem:
            continue
        data = _load_json(p)
        if isinstance(data, list) and data:
            runs[_run_label(p)] = data
    return runs

def run_paper(metrics=None, prose=None):
    base = pathlib.Path(__file__).resolve().parents[3]
    runs = gather_runs(base)
    ev = _load_json(base / "experiments" / "evaluation_results.json") or {}
    results_section = build_results_section(runs, ev, prose)

    tex_path = base / "paper" / "main.tex"
    if tex_path.exists():
        tex = tex_path.read_text(encoding="utf-8")
        pattern = r"\\section\{Results.*?(?=\\section\{Conclusion)"
        if re.search(pattern, tex, flags=re.DOTALL):
            tex = re.sub(pattern, lambda m: results_section + "\n", tex, flags=re.DOTALL)
        else:
            tex = tex.replace("\\bibliographystyle", results_section + "\n\\bibliographystyle")
        tex_path.write_text(tex, encoding="utf-8")
    print(f"Paper patched -> {tex_path} (runs: {list(runs)})")
    return results_section
